### ISSUE TITLE
Fix handling of store() when the original object belongs to another user.

### ISSUE THREAD

**Issue by blink1073** [metabolite-atlas/metatlas#41]

**Comment by blink1073** [comment]
Fixed in 2a3ab45fd01561f9589b60cafb35b606c7a26d6d

**Comment by benbowen** [comment]
One of the updates since yesterday afternoon changed the retrieve
functionality.  I'm getting an error now:

In [2]:

allCompounds = metob.retrieve('Compounds')

print len(allCompounds)

---------------------------------------------------------------------------ProgrammingError
                         Traceback (most recent call
last)<ipython-input-2-b49973e5d0d5> in <module>()----> 1 allCompounds
= metob.retrieve('Compounds')      2 print len(allCompounds)
/global/project/projectdirs/metatlas/anaconda/lib/python2.7/site-packages/metatlas/metatlas_objects.py
in retrieve(object_type, **kwargs)    320             raise
ValueError('Invalid column name, valid columns: %s' % keys)    321
    else:--> 322             raise(e)    323     prev_uuids =
[i['prev_uid'] for i in items]    324     items = [klass(**i) for i in
items
ProgrammingError: (pymysql.err.ProgrammingError) (1064, u"You have an
error in your SQL syntax; check the manual that corresponds to your
MySQL server version for the right syntax to use near ''compounds'' at
line 1") [SQL: u"select * from 'compounds' "]

**Comment by blink1073** [comment]
Fixed.

**Comment by benbowen** [comment]
Weird, I'm still getting the same error:

In [2]:

allCompounds = metob.retrieve('Compounds')

print len(allCompounds)

---------------------------------------------------------------------------ProgrammingError
                         Traceback (most recent call
last)<ipython-input-2-b49973e5d0d5> in <module>()----> 1 allCompounds
= metob.retrieve('Compounds')      2 print len(allCompounds)
/global/project/projectdirs/metatlas/anaconda/lib/python2.7/site-packages/metatlas/metatlas_objects.py
in retrieve(object_type, **kwargs)    325             raise
ValueError('Invalid column name, valid columns: %s' % keys)    326
    else:--> 327             raise(e)    328     prev_uuids =
[i['prev_uid'] for i in items]    329     items = [klass(**i) for i in
items
ProgrammingError: (pymysql.err.ProgrammingError) (1064, u"You have an
error in your SQL syntax; check the manual that corresponds to your
MySQL server version for the right syntax to use near ''compounds'' at
line 1") [SQL: u"select * from 'compounds'"]

**Comment by blink1073** [comment]
Fixed, there was a syntax difference between sqlite and mysql, figures…

allCompounds = metob.retrieve('Compounds')
​
print len(allCompounds)
11862
